const DIMS=["abstinence","love","lust","appetite","material","possessive"];
const LABELS=["克制欲","爱欲","情欲","食欲","物欲","占有欲"];
const q=(text,options)=>({text,options:options.map(([text,score])=>({text,score}))});
const QUESTIONS=[
q("如果能从下面随手带走一样东西，你最想拿哪件？",[["一本让人安静下来的书",{abstinence:1,material:1}],["一对精致又好看的杯子",{love:1,material:1}],["一盆正在长新叶的绿植",{abstinence:2}],["一副沉浸感很强的耳机",{lust:1,abstinence:1}]]),
q("得到一张“任选一件”的兑换券，你会怎么用？",[["换平时舍不得买的小物件",{material:2}],["换一件能让房间更温柔的东西",{love:1,material:1}],["换限量、编号、独一份的收藏",{possessive:2,material:1}],["先留着，暂时不急着用",{abstinence:2}]]),
q("平时你最容易囤下什么？",[["喜欢的文具、玩具或手办",{material:2,possessive:1}],["常用的生活必需品",{abstinence:1,material:1}],["看上的都想多备一点",{possessive:2,material:2}],["用完再买，基本不囤",{abstinence:2}]]),
q("下面哪一种房间最合你心意？",[["东西不少，但每件都很喜欢",{material:2,appetite:1}],["灯光柔和，让人想慢慢待着",{love:2}],["空间紧凑，每个角落都井然有序",{possessive:2,abstinence:1}],["干净简单，几乎没有杂物",{abstinence:2}]]),
q("压力很大时，你通常怎样让自己缓过来？",[["买点一直想要的东西",{material:2}],["找朋友好好聚一场",{love:1,appetite:1}],["刷剧、打游戏或尽情放空",{lust:1,appetite:1}],["换个地方走走看看",{abstinence:1,material:1}]]),
q("哪一幅画面更适合做你的手机壁纸？",[["夜市灯牌与模糊人群",{appetite:1,material:1}],["黄昏里并排的两个影子",{love:2}],["一条通往远处的上坡路",{possessive:1,abstinence:1}],["雨滴落在窗上的特写",{abstinence:2}]]),
q("你更常被哪种音乐吸引？",[["热烈、有节奏、听了想动",{appetite:1,lust:1}],["甜甜的、带点恋爱气息",{love:2}],["冷酷有力量、态度鲜明",{possessive:1,lust:1}],["安静克制、适合独处",{abstinence:2}]]),
q("只能选择一种天气长期生活，你会选？",[["明亮晴天，适合出门逛逛",{material:1,appetite:1}],["温柔黄昏，适合慢慢散步",{love:2}],["大风来临，有种变化将至的刺激",{lust:1,possessive:1}],["细雨绵绵，适合待在房间",{abstinence:2}]]),
q("下面哪一种感受最让你难以接受？",[["被束缚、不能按自己的方式活",{abstinence:1,possessive:1}],["被重要的人讨厌或疏远",{love:2,possessive:1}],["努力很久却没有成功",{possessive:2,material:1}],["想要的始终得不到满足",{appetite:1,material:1,lust:1}]]),
q("走进一家小店，你最可能记住哪个细节？",[["货架上密密摆满的小物件",{material:2}],["门口那盏让人放松的暖灯",{love:1,lust:1}],["柜台上特殊又醒目的编号牌",{possessive:2}],["角落里一张无人坐的椅子",{abstinence:2}]]),
q("下面哪件事最让你觉得浪漫？",[["独自来一场说走就走的旅行",{abstinence:1,material:1}],["和喜欢的人一起看流星",{love:2,lust:1}],["种下一棵树，许多年后再回来",{love:1,abstinence:1}],["写信给很多年后的自己",{abstinence:2}]]),
q("给你一个漂亮盒子，你最想装进什么？",[["这些年留下来的小玩意",{material:2,possessive:1}],["有纪念意义的票根和照片",{love:2}],["只属于自己的秘密纸条",{possessive:2,lust:1}],["什么也不放，空着就很好",{abstinence:2}]]),
q("以下哪件事最容易给你带来快乐？",[["吃到惦记很久的美食",{appetite:2}],["和真正喜欢的人待在一起",{love:2}],["学习或工作拿到好成绩",{possessive:2,material:1}],["专心做自己感兴趣的事",{abstinence:1,material:1}]]),
q("四个没有标签的盒子，你会先打开哪一个？",[["沉甸甸、像装满东西的盒子",{material:2,appetite:1}],["系着柔软丝带、有岁月痕迹的盒子",{love:2,lust:1}],["印着一串特殊编号的盒子",{possessive:2}],["没有装饰的纯白盒子",{abstinence:2}]]),
q("如果一张照片只能留下一个细节，你选？",[["桌角闪闪发亮的小装饰",{material:2}],["两只靠得很近的杯子",{love:1,lust:1}],["画面中心最醒目的椅子",{possessive:2}],["窗外一小片空白天空",{abstinence:2}]]),
q("你更喜欢哪类颜色带来的感觉？",[["明亮饱满，让人马上有精神",{appetite:1,material:1}],["柔和温暖，让人想靠近",{love:2}],["浓烈抢眼，一眼就能记住",{lust:2,possessive:1}],["清淡低调，怎么看都不累",{abstinence:2}]]),
q("窗台上只能摆一件东西，你会放？",[["颜色好看的玻璃瓶",{material:2}],["一束快要盛开的花",{love:1,lust:1}],["造型特别、很难买到的摆件",{possessive:2,material:1}],["什么都不摆，留一片空白",{abstinence:2}]]),
q("以下哪一种画面最让你不舒服？",[["漂亮陈列里突然缺了一件",{material:2}],["本来成对的东西只剩一个",{love:2}],["整齐排列被人随手打乱",{possessive:2}],["干净白纸上多出一道划痕",{abstinence:2}]]),
q("一本书只能留下最后一句，你更喜欢？",[["“他终于推开那扇亮着灯的门。”",{material:1,appetite:1}],["“许多年后，他们依然认出了彼此。”",{love:2}],["“那一刻，所有目光都投向了他。”",{possessive:2}],["“风吹过来，他没有带走任何东西。”",{abstinence:2}]]),
q("你觉得自己是一个有野心的人吗？",[["是，我心里一直有想抵达的地方",{possessive:2,material:1}],["不算是，舒服自在对我更重要",{abstinence:1}]])
];
const PROFILES=[
{name:"随心所欲",v:[5,60,70,85,95,40],comment:"你随心所欲的样子，别人羡慕不来。",quote:"不是贪心，只是不想把人生过得太委屈。",p:["你很懂得照顾自己的感受。想吃、想买、想体验时，只要条件允许，你愿意及时满足自己。","你也期待亲密和心动，但不会为了关系放弃自己的生活。爱很重要，舒服地做自己同样重要。","你的人生关键词是坦率：承认想要，认真享受，也愿意为自己的选择负责。"]},
{name:"情深似海",v:[15,95,80,50,55,60],comment:"对爱真情实感，也更容易遇见良人。",quote:"不是恋爱脑，只是每一次认真都很真。",p:["你对感情的投入度很高。真正喜欢一个人后，会记住细节，也会下意识替对方考虑。","心动对你不只是浪漫想象，还包含真实的吸引与靠近。你渴望双向、明确、稳定的回应。","你需要留意别让体贴变成过度付出。保留边界，反而能让深情走得更远。"]},
{name:"超强占有欲",v:[10,60,65,55,70,95],comment:"凭实力争取，也想把重要的事牢牢守住。",quote:"不是所有都要，但真正想要的不会轻易让。",p:["你对目标、机会和关系都有很强的领地意识。一旦认定，就不喜欢半途而废。","你的胜负心能带来行动力，也会让你在不确定中变得敏感。越重要，越想确认它是否属于自己。","把控制感转化成建设感，会让你更有力量：提升能力、说清需求，同时尊重彼此空间。"]},
{name:"深情好色",v:[5,80,95,45,60,75],comment:"既要灵魂共振，也要心跳加速。",quote:"不只看脸，只是恰好也很吃吸引力。",p:["你很容易被眼神、声音、距离与氛围击中，对心动的感知比大多数人敏锐。","但你并非只追求刺激。真正让你上头的人，既要有吸引力，也要能让你安心和认真。","你适合坦诚而有边界的关系：承认欲望、尊重同意，也把热烈留给同样认真的人。"]},
{name:"清心寡欲",v:[90,10,15,10,15,10],comment:"普通诱惑，很难打乱你的节奏。",quote:"不是冷淡，只是很多东西并没有那么必要。",p:["你对物质、热闹和即时刺激的需求偏低，更喜欢安静、清爽、可控的生活。","你不是没有感情，而是不愿为了不确定的人和事消耗太多自己。","克制让你稳定，也别忘了给好奇心留一点位置。偶尔允许自己想要，并不等于失去掌控。"]},
{name:"无欲无求",v:[98,5,5,5,5,5],comment:"看淡很多事，也很少被外界牵着走。",quote:"人间很好，只是我更愿意安静旁观。",p:["你的内在需求很简洁，不太需要靠拥有、比较或被关注来证明自己。","你享受留白，能够独处，也能对许多诱惑保持距离。","如果这种平静让你舒服，它就是优势；如果它来自疲惫，也请允许自己休息和重新连接。"]},
{name:"干饭至上",v:[10,40,45,95,60,30],comment:"天大的事，也要先吃顿好的。",quote:"没有什么坎是一顿饭过不去的。",p:["你对生活的快乐入口非常明确：好吃、好喝、舒服，是最直接也最可靠的能量补给。","你并不肤浅，只是懂得先把具体日子过好，再处理抽象烦恼。","享受美食的同时照顾身体和预算，你的快乐就能更稳定、更长久。"]},
{name:"恋爱上头",v:[10,95,70,40,50,80],comment:"嘴上说随缘，真正喜欢后比谁都认真。",quote:"嘴上还在随缘，心里已经演到大结局。",p:["你对恋爱既期待又认真，遇到真正喜欢的人，很容易迅速投入情绪与想象。","你重视偏爱和确定性，因此暧昧不清最容易消耗你。","慢一点确认事实，保留自己的生活节奏，会让你的真心落在更值得的人身上。"]},
{name:"啥都想要",v:[10,55,60,70,95,70],comment:"喜欢的东西太多，而人生又太短。",quote:"不是啥都要，只是眼光刚好很好。",p:["你对世界有旺盛兴趣：好东西、好体验、好关系，都能迅速激发你的行动力。","你愿意争取，也不太喜欢用克制包装真实愿望。","当选择太多时，先分清“真想要”和“怕错过”，会让每一次拥有都更有价值。"]},
{name:"野心不小",v:[15,45,50,55,80,95],comment:"看似云淡风轻，心里其实早有方向。",quote:"可以不说，但目标一直都在。",p:["你对成绩、稀缺机会和掌控感有明确需求，不甘心长期停留在原地。","这种野心未必张扬，却会推动你持续积累资源与能力。","别只盯着终点。把目标拆成稳定行动，也给关系与身体留出余量，才能走得更久。"]},
{name:"及时行乐",v:[5,60,80,80,80,50],comment:"快乐今天能拥有，就不想拖到明天。",quote:"人生苦短，先认真快乐再说。",p:["你重视当下体验，不喜欢为了遥远的未来把现在过成等待。","你对美食、消费、心动和新鲜感都有较高敏感度，也因此很会给生活制造亮点。","及时行乐不等于没有计划。留好安全垫，快乐就不必在第二天变成压力。"]},
{name:"人间清醒",v:[80,30,25,35,40,35],comment:"不是没有欲望，只是不容易被欲望牵着走。",quote:"我有想要的，只是不轻易上头。",p:["你能感受到欲望，却很少马上被它推动。比起即时满足，你更看重值不值得、是否合适。","你在关系与物质上都较有边界，能够拒绝比较，也能及时从消耗中抽身。","清醒是保护，也是筛选。偶尔让感性参与决定，会给稳定生活带来意外的温度。"]}
];
let state={page:"home",index:0,answers:Array(QUESTIONS.length).fill(null),result:null};
const app=document.querySelector("#app");
const max=DIMS.reduce((o,d)=>(o[d]=QUESTIONS.reduce((sum,x)=>sum+Math.max(...x.options.map(y=>y.score[d]||0)),0),o),{});
function header(extra=""){return `<header class="topbar"><div class="brand"><span class="brand-icon">欲</span><span>欲望测试</span></div>${extra||'<span class="tag">DESIRE CHECK-IN</span>'}</header>`}
function save(){localStorage.setItem("desireQuiz",JSON.stringify({index:state.index,answers:state.answers}))}
function home(){state.page="home";app.innerHTML=`<div class="shell">${header()}<section class="hero"><div class="hero-mark">欲</div><div class="tag">DESIRE CHECK-IN</div><h1>你的什么<br><span class="gradient">欲望最强？</span></h1><p class="lead">一次不太正经的内心欲望小测试</p><p class="desc">每个人心里都藏着一些想要。有人向往亲密，有人偏爱拥有，也有人只想吃好喝好。别急着给自己贴标签，测完再看。</p></section><div class="feature-grid"><div class="feature"><b>20</b><span>道情境题</span></div><div class="feature"><b>6</b><span>个欲望维度</span></div><div class="feature"><b>3′</b><span>轻松完成</span></div></div><button class="primary" id="start">开始检测 →</button><p class="meta">进度自动保存在当前浏览器</p><p class="fine">本测试仅供娱乐，不具备专业心理学效力</p></div>`;document.querySelector("#start").onclick=start}
function start(){const old=localStorage.getItem("desireQuiz");if(old){try{const x=JSON.parse(old);state.answers=x.answers||state.answers;state.index=Math.min(x.index||0,19)}catch{}}state.page="test";renderQuestion()}
function renderQuestion(){const x=QUESTIONS[state.index],chosen=state.answers[state.index];app.innerHTML=`<div class="shell"><header class="topbar test-head"><button class="back" aria-label="返回首页">←</button><div class="brand">欲望测试</div><span class="count">${String(state.index+1).padStart(2,"0")} / 20</span></header><div class="progress"><span style="width:${(state.index+1)*5}%"></span></div><section class="question"><div class="eyebrow">请选择最接近你的一项</div><h2>${x.text}</h2><div class="options">${x.options.map((o,i)=>`<button class="option ${chosen===i?"selected":""}" data-i="${i}"><span class="letter">${"ABCD"[i]}</span><span>${o.text}</span></button>`).join("")}</div><div class="navrow">${state.index?'<button class="previous">← 上一题</button>':"<span></span>"}<span>选择后自动跳转</span></div></section></div>`;document.querySelector(".back").onclick=home;document.querySelectorAll(".option").forEach(b=>b.onclick=()=>choose(+b.dataset.i));const p=document.querySelector(".previous");if(p)p.onclick=()=>{state.index--;save();renderQuestion()}}
function choose(i){state.answers[state.index]=i;save();document.querySelectorAll(".option").forEach((b,j)=>b.classList.toggle("selected",i===j));setTimeout(()=>{if(state.index<19){state.index++;save();renderQuestion()}else generate()},330)}
function generate(){state.page="loading";app.innerHTML=`<div class="shell"><div class="loading"><div><div class="spinner"></div><h2>正在生成你的欲望报告</h2><p class="desc">把零散的选择拼成一张内心地图…</p></div></div></div>`;setTimeout(()=>{state.result=calculate();renderResult()},900)}
function calculate(){const raw=Object.fromEntries(DIMS.map(d=>[d,0]));QUESTIONS.forEach((x,i)=>{const opt=x.options[state.answers[i]??0];DIMS.forEach(d=>raw[d]+=opt.score[d]||0)});const values=DIMS.map(d=>Math.round(raw[d]/max[d]*100));let best=PROFILES[0],dist=Infinity;PROFILES.forEach(p=>{const n=p.v.reduce((s,v,i)=>s+(v-values[i])**2,0);if(n<dist){dist=n;best=p}});return {...best,values}}
function radar(values){const cx=170,cy=160,R=105,pt=(r,i)=>{const a=-Math.PI/2+i*Math.PI/3;return [cx+Math.cos(a)*r,cy+Math.sin(a)*r]},poly=r=>DIMS.map((_,i)=>pt(r,i).join(",")).join(" ");const shape=values.map((v,i)=>pt(R*v/100,i).join(",")).join(" ");return `<svg class="radar" viewBox="0 0 340 325" role="img" aria-label="六维欲望雷达图">${[.25,.5,.75,1].map(x=>`<polygon points="${poly(R*x)}" fill="none" stroke="#eadfd7"/>`).join("")}${DIMS.map((_,i)=>{const p=pt(R,i);return `<line x1="${cx}" y1="${cy}" x2="${p[0]}" y2="${p[1]}" stroke="#eadfd7"/>`}).join("")}<polygon points="${shape}" fill="rgba(255,91,34,.22)" stroke="#ff5b22" stroke-width="2"/>${values.map((v,i)=>{const p=pt(R*v/100,i);return `<circle cx="${p[0]}" cy="${p[1]}" r="3.5" fill="#ff5b22"/>`}).join("")}${LABELS.map((t,i)=>{const p=pt(R+24,i);return `<text x="${p[0]}" y="${p[1]}" text-anchor="middle" dominant-baseline="middle">${t} ${values[i]}</text>`}).join("")}</svg>`}
function renderResult(){state.page="result";const r=state.result;app.innerHTML=`<div class="shell result">${header()}<article class="result-card"><div class="result-label">你的欲望检测结果</div><h1 class="gradient">${r.name}</h1><p class="comment">${r.comment}</p><div class="radar-wrap">${radar(r.values)}</div><div class="quote">“${r.quote}”</div><div class="analysis"><h3>你的内心报告</h3>${r.p.map(x=>`<p>${x}</p>`).join("")}</div><div class="actions"><button class="secondary" id="copy">复制结果</button><button class="primary" id="again">重新测试</button></div></article><p class="fine">答案仅在你的浏览器中计算，不会上传</p></div>`;document.querySelector("#again").onclick=()=>{localStorage.removeItem("desireQuiz");state={page:"test",index:0,answers:Array(20).fill(null),result:null};renderQuestion()};document.querySelector("#copy").onclick=async()=>{const text=`我的欲望测试结果是「${r.name}」：${r.quote}`;try{await navigator.clipboard.writeText(text);toast("结果已复制")}catch{toast("复制失败，请手动截图保存")}}}
function toast(t){const n=document.createElement("div");n.className="toast";n.textContent=t;document.body.appendChild(n);setTimeout(()=>n.remove(),1800)}
home();
